# Generated by Django 5.0.6 on 2024-06-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='faborito',
            field=models.BooleanField(default=False),
        ),
    ]
