# Generated by Django 5.0.6 on 2024-05-27 05:39

import django.db.models.deletion
import reconocimientoFacial.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimientoFacial', '0003_entrenardnn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolectar_datos',
            name='imagen',
            field=models.ImageField(upload_to=reconocimientoFacial.models.carga_personalizada),
        ),
        migrations.CreateModel(
            name='ModeloEntrenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_modelo', models.FileField(upload_to=reconocimientoFacial.models.carga_personalizada)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='entrenarDNN',
        ),
    ]
