# Generated by Django 5.0.6 on 2024-05-27 06:40

import django.db.models.deletion
import reconocimientoFacial.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimientoFacial', '0005_alter_recolectar_datos_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolectar_datos',
            name='imagen',
            field=models.ImageField(upload_to=reconocimientoFacial.models.carga_personalizada),
        ),
        migrations.CreateModel(
            name='FotosDondeApareces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to=reconocimientoFacial.models.FotosDondeApareces.guardarEnAlbum)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
