# Generated by Django 5.0.6 on 2024-05-27 06:50

import reconocimientoFacial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimientoFacial', '0007_alter_recolectar_datos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolectar_datos',
            name='imagen',
            field=models.ImageField(upload_to=reconocimientoFacial.models.carga_personalizada),
        ),
    ]
