# Generated by Django 5.0.6 on 2024-05-27 09:04

import django.db.models.deletion
import reconocimientoFacial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
        ('reconocimientoFacial', '0008_alter_recolectar_datos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotosdondeapareces',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.album'),
        ),
        migrations.AlterField(
            model_name='recolectar_datos',
            name='imagen',
            field=models.ImageField(upload_to=reconocimientoFacial.models.carga_personalizada),
        ),
    ]
